outdir: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/IGV_clusters/results_H3K27ac
barcodes_dir: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/IGV_clusters/barcodes_H3K27ac/
barcodetag: CB
threads: 8
binsize: 10
normalize: RPGC                       # RPGC / CPM / BPM are more comparable across clusters
effective_genome_size: 2913022398     # GRCh38; mm10 = 2652783500
blacklist: ''                         # optional path to a blacklist BED, or '' to skip
merge_across_experiments: true    # true -> also pool each cluster across experiments

bams:
  #MS3BL1_CT.H3K27ac_MS058: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/MS3BL1_CT/H3K27ac_MS058_TCGAGCTA/cellranger/outs/possorted_bam.bam
  #MS3BL1_CT.H3K27ac_MS381: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/MS3BL1_CT/H3K27ac_MS381_CCTATCCT/cellranger/outs/possorted_bam.bam
  #MS3BL1_CT.H3K27ac_MS549: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/MS3BL1_CT/H3K27ac_MS549_AGCTTGAC/cellranger/outs/possorted_bam.bam
  #MS3BL2_CT.H3K27ac_MS058: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/MS3BL2_CT/H3K27ac_MS058_TCGAGCTA/cellranger/outs/possorted_bam.bam
  #MS3BL2_CT.H3K27ac_MS381: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/MS3BL2_CT/H3K27ac_MS381_CCTATCCT/cellranger/outs/possorted_bam.bam
  #MS3BL2_CT.H3K27ac_MS549: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/MS3BL2_CT/H3K27ac_MS549_AGCTTGAC/cellranger/outs/possorted_bam.bam
  #MS549_CT.H3K27ac:        /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/MS549_CT/H3K27ac_CCTATCCT/cellranger/outs/possorted_bam.bam
  PBMC_CT_H3K27ac: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/PBMC/PBMC_CT/H3K27ac_CCTATCCT/cellranger/outs/possorted_bam.bam
  PBMC_DynaTag_H3K27ac: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/PBMC/PBMC_DynaTag/H3K27ac_CCTATCCT/cellranger/outs/possorted_bam.bam
