outdir: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/IGV_clusters/results_H3K27me3
barcodes_dir: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/IGV_clusters/barcodes_H3K27me3/
barcodetag: CB
threads: 20
binsize: 10
normalize: RPGC                       # RPGC / CPM / BPM are more comparable across clusters
effective_genome_size: 2913022398     # GRCh38; mm10 = 2652783500
blacklist: ''                         # optional path to a blacklist BED, or '' to skip
merge_across_experiments: True     # true -> also pool each cluster across experiments
macs_genome: hs

bams:
  #MS3BL1_CT.H3K27me3_MS058: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/MS3BL1_CT/H3K27me3_MS058_GCTTCGAA/cellranger/outs/possorted_bam.bam
  #MS3BL1_CT.H3K27me3_MS381: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/MS3BL1_CT/H3K27me3_MS381_ATAGAGGC/cellranger/outs/possorted_bam.bam
  #MS3BL1_CT.H3K27me3_MS549: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/MS3BL1_CT/H3K27me3_MS549_TACGTCGA/cellranger/outs/possorted_bam.bam
  #MS3BL2_CT.H3K27me3_MS058: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/MS3BL2_CT/H3K27me3_MS058_GCTTCGAA/cellranger/outs/possorted_bam.bam
  #MS3BL2_CT.H3K27me3_MS381: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/MS3BL2_CT/H3K27me3_MS381_ATAGAGGC/cellranger/outs/possorted_bam.bam
  #MS3BL2_CT.H3K27me3_MS549: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/MS3BL2_CT/H3K27me3_MS549_TACGTCGA/cellranger/outs/possorted_bam.bam
  #MS549_CT.H3K27me3:        /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/MS549_CT/H3K27me3_ATAGAGGC/cellranger/outs/possorted_bam.bam
  PBMC_CT_H3K27me3: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/PBMC/PBMC_CT/H3K27me3_ATAGAGGC/cellranger/outs/possorted_bam.bam
  PBMC_DynaTag_H3K27me3: /date/gcb/gcb_MZ/multiNanoCT/samples/PBMCs-MS/PBMC/PBMC_DynaTag/H3K27me3_ATAGAGGC/cellranger/outs/possorted_bam.bam
